### ISSUE TITLE
UI improvements for the game

### ISSUE THREAD

**Issue by thisisharsh7** [Nktech-Official/Blox-Smash#4]
Clickable items should have **cursor pointers**, while **unclickable items** such as score, next, and level should not. The buttons should be more **interactive.**  A line can be drawn between the score, next, level, and many other things. I would like to contribute on this . Please assign me this as a part of **hacktoberfest**.

**Comment by parth-verma7** [comment]
Hi @thisisharsh7 I would like to work on this issue, can u please assign it to me?

**Comment by thisisharsh7** [comment]
@parth-verma7 I am not a maintainer of this project, but I ask that the maintainer assign this issue to me.
